package paquete;
// Generated 29 nov. 2021 16:39:36 by Hibernate Tools 5.4.32.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Films generated by hbm2java
 */
public class Films implements java.io.Serializable {

	private int id;
	private String episode;
	private String title;
	private Set characterses = new HashSet(0);
	private Set deathses = new HashSet(0);

	public Films() {
	}

	public Films(int id) {
		this.id = id;
	}

	public Films(int id, String episode, String title, Set characterses, Set deathses) {
		this.id = id;
		this.episode = episode;
		this.title = title;
		this.characterses = characterses;
		this.deathses = deathses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEpisode() {
		return this.episode;
	}

	public void setEpisode(String episode) {
		this.episode = episode;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set getCharacterses() {
		return this.characterses;
	}

	public void setCharacterses(Set characterses) {
		this.characterses = characterses;
	}

	public Set getDeathses() {
		return this.deathses;
	}

	public void setDeathses(Set deathses) {
		this.deathses = deathses;
	}

}
